[project]
name = "budget"
version = "0.1.0"
description = ""
authors = [
    {name = "Elson Lim",email = "elsonlimengvern@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "duckdb (>=1.5.3,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "psycopg2-binary (>=2.9)",
    "PyYAML (>=6.0.1)",
    "fastapi (>=0.115.0)",
    "uvicorn (>=0.30.0)",
    "pydantic (>=2.0)",
    "pytz (>=2024.1)"
]

[tool.poetry]
packages = [
    { include = "pipeline" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.0,<10.0.0)"
]
